allowBuilds:
  "@swc/core": true
  msw: true
minimumReleaseAgeExclude:
  - "@tanstack/react-router@1.170.27"
  - "@tanstack/router-core@1.171.22"
  - "@tanstack/router-generator@1.167.28"
  - "@tanstack/router-plugin@1.168.30"
