/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google-callback'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as AuthenticatedCatalogueCategoriesRouteImport } from './routes/_authenticated/catalogue/categories'
import { Route as AuthenticatedCatalogueImportRouteImport } from './routes/_authenticated/catalogue/import'
import { Route as AuthenticatedCatalogueProductsRouteImport } from './routes/_authenticated/catalogue/products'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedInventoryAdjustmentsRouteImport } from './routes/_authenticated/inventory/adjustments'
import { Route as AuthenticatedInventoryAlertsRouteImport } from './routes/_authenticated/inventory/alerts'
import { Route as AuthenticatedInventoryConsumptionRouteImport } from './routes/_authenticated/inventory/consumption'
import { Route as AuthenticatedInventoryCountsRouteImport } from './routes/_authenticated/inventory/counts'
import { Route as AuthenticatedInventoryMovementsRouteImport } from './routes/_authenticated/inventory/movements'
import { Route as AuthenticatedInventoryOpeningStockRouteImport } from './routes/_authenticated/inventory/opening-stock'
import { Route as AuthenticatedInventoryReorderRouteImport } from './routes/_authenticated/inventory/reorder'
import { Route as AuthenticatedInventoryStockRouteImport } from './routes/_authenticated/inventory/stock'
import { Route as AuthenticatedInventoryTransfersRouteImport } from './routes/_authenticated/inventory/transfers'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedOfflineReviewRouteImport } from './routes/_authenticated/offline/review'
import { Route as AuthenticatedPurchasingIndexRouteImport } from './routes/_authenticated/purchasing/index'
import { Route as AuthenticatedRegistersIndexRouteImport } from './routes/_authenticated/registers/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsBusinessRouteImport } from './routes/_authenticated/settings/business'
import { Route as AuthenticatedSettingsReceiptsRouteImport } from './routes/_authenticated/settings/receipts'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedInventoryBatchesIndexRouteImport } from './routes/_authenticated/inventory/batches/index'
import { Route as AuthenticatedRegistersRegisterIdFavouritesRouteImport } from './routes/_authenticated/registers/$registerId.favourites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google-callback',
  path: '/auth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogueCategoriesRoute =
  AuthenticatedCatalogueCategoriesRouteImport.update({
    id: '/catalogue/categories',
    path: '/catalogue/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogueImportRoute =
  AuthenticatedCatalogueImportRouteImport.update({
    id: '/catalogue/import',
    path: '/catalogue/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogueProductsRoute =
  AuthenticatedCatalogueProductsRouteImport.update({
    id: '/catalogue/products',
    path: '/catalogue/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAdjustmentsRoute =
  AuthenticatedInventoryAdjustmentsRouteImport.update({
    id: '/inventory/adjustments',
    path: '/inventory/adjustments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAlertsRoute =
  AuthenticatedInventoryAlertsRouteImport.update({
    id: '/inventory/alerts',
    path: '/inventory/alerts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryConsumptionRoute =
  AuthenticatedInventoryConsumptionRouteImport.update({
    id: '/inventory/consumption',
    path: '/inventory/consumption',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryCountsRoute =
  AuthenticatedInventoryCountsRouteImport.update({
    id: '/inventory/counts',
    path: '/inventory/counts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryMovementsRoute =
  AuthenticatedInventoryMovementsRouteImport.update({
    id: '/inventory/movements',
    path: '/inventory/movements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryOpeningStockRoute =
  AuthenticatedInventoryOpeningStockRouteImport.update({
    id: '/inventory/opening-stock',
    path: '/inventory/opening-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryReorderRoute =
  AuthenticatedInventoryReorderRouteImport.update({
    id: '/inventory/reorder',
    path: '/inventory/reorder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockRoute =
  AuthenticatedInventoryStockRouteImport.update({
    id: '/inventory/stock',
    path: '/inventory/stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryTransfersRoute =
  AuthenticatedInventoryTransfersRouteImport.update({
    id: '/inventory/transfers',
    path: '/inventory/transfers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfflineReviewRoute =
  AuthenticatedOfflineReviewRouteImport.update({
    id: '/offline/review',
    path: '/offline/review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasingIndexRoute =
  AuthenticatedPurchasingIndexRouteImport.update({
    id: '/purchasing/',
    path: '/purchasing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistersIndexRoute =
  AuthenticatedRegistersIndexRouteImport.update({
    id: '/registers/',
    path: '/registers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBusinessRoute =
  AuthenticatedSettingsBusinessRouteImport.update({
    id: '/settings/business',
    path: '/settings/business',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsReceiptsRoute =
  AuthenticatedSettingsReceiptsRouteImport.update({
    id: '/settings/receipts',
    path: '/settings/receipts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryBatchesIndexRoute =
  AuthenticatedInventoryBatchesIndexRouteImport.update({
    id: '/inventory/batches/',
    path: '/inventory/batches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistersRegisterIdFavouritesRoute =
  AuthenticatedRegistersRegisterIdFavouritesRouteImport.update({
    id: '/registers/$registerId/favourites',
    path: '/registers/$registerId/favourites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pos': typeof AuthenticatedPosRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/catalogue/categories': typeof AuthenticatedCatalogueCategoriesRoute
  '/catalogue/import': typeof AuthenticatedCatalogueImportRoute
  '/catalogue/products': typeof AuthenticatedCatalogueProductsRoute
  '/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory/alerts': typeof AuthenticatedInventoryAlertsRoute
  '/inventory/consumption': typeof AuthenticatedInventoryConsumptionRoute
  '/inventory/counts': typeof AuthenticatedInventoryCountsRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/opening-stock': typeof AuthenticatedInventoryOpeningStockRoute
  '/inventory/reorder': typeof AuthenticatedInventoryReorderRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/offline/review': typeof AuthenticatedOfflineReviewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/receipts': typeof AuthenticatedSettingsReceiptsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/purchasing/': typeof AuthenticatedPurchasingIndexRoute
  '/registers/': typeof AuthenticatedRegistersIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/registers/$registerId/favourites': typeof AuthenticatedRegistersRegisterIdFavouritesRoute
  '/inventory/batches/': typeof AuthenticatedInventoryBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pos': typeof AuthenticatedPosRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/catalogue/categories': typeof AuthenticatedCatalogueCategoriesRoute
  '/catalogue/import': typeof AuthenticatedCatalogueImportRoute
  '/catalogue/products': typeof AuthenticatedCatalogueProductsRoute
  '/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory/alerts': typeof AuthenticatedInventoryAlertsRoute
  '/inventory/consumption': typeof AuthenticatedInventoryConsumptionRoute
  '/inventory/counts': typeof AuthenticatedInventoryCountsRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/opening-stock': typeof AuthenticatedInventoryOpeningStockRoute
  '/inventory/reorder': typeof AuthenticatedInventoryReorderRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/offline/review': typeof AuthenticatedOfflineReviewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/receipts': typeof AuthenticatedSettingsReceiptsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/purchasing': typeof AuthenticatedPurchasingIndexRoute
  '/registers': typeof AuthenticatedRegistersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/registers/$registerId/favourites': typeof AuthenticatedRegistersRegisterIdFavouritesRoute
  '/inventory/batches': typeof AuthenticatedInventoryBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/_authenticated/catalogue/categories': typeof AuthenticatedCatalogueCategoriesRoute
  '/_authenticated/catalogue/import': typeof AuthenticatedCatalogueImportRoute
  '/_authenticated/catalogue/products': typeof AuthenticatedCatalogueProductsRoute
  '/_authenticated/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/_authenticated/inventory/alerts': typeof AuthenticatedInventoryAlertsRoute
  '/_authenticated/inventory/consumption': typeof AuthenticatedInventoryConsumptionRoute
  '/_authenticated/inventory/counts': typeof AuthenticatedInventoryCountsRoute
  '/_authenticated/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/_authenticated/inventory/opening-stock': typeof AuthenticatedInventoryOpeningStockRoute
  '/_authenticated/inventory/reorder': typeof AuthenticatedInventoryReorderRoute
  '/_authenticated/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/_authenticated/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/_authenticated/offline/review': typeof AuthenticatedOfflineReviewRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/_authenticated/settings/receipts': typeof AuthenticatedSettingsReceiptsRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/purchasing/': typeof AuthenticatedPurchasingIndexRoute
  '/_authenticated/registers/': typeof AuthenticatedRegistersIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/registers/$registerId/favourites': typeof AuthenticatedRegistersRegisterIdFavouritesRoute
  '/_authenticated/inventory/batches/': typeof AuthenticatedInventoryBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/plans'
    | '/register'
    | '/dashboard'
    | '/onboarding'
    | '/pos'
    | '/returns'
    | '/sales'
    | '/auth/google-callback'
    | '/invite/accept'
    | '/catalogue/categories'
    | '/catalogue/import'
    | '/catalogue/products'
    | '/inventory/adjustments'
    | '/inventory/alerts'
    | '/inventory/consumption'
    | '/inventory/counts'
    | '/inventory/movements'
    | '/inventory/opening-stock'
    | '/inventory/reorder'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/offline/review'
    | '/settings/billing'
    | '/settings/business'
    | '/settings/receipts'
    | '/settings/security'
    | '/inventory/'
    | '/locations/'
    | '/notifications/'
    | '/purchasing/'
    | '/registers/'
    | '/reports/'
    | '/staff/'
    | '/registers/$registerId/favourites'
    | '/inventory/batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/plans'
    | '/register'
    | '/dashboard'
    | '/onboarding'
    | '/pos'
    | '/returns'
    | '/sales'
    | '/auth/google-callback'
    | '/invite/accept'
    | '/catalogue/categories'
    | '/catalogue/import'
    | '/catalogue/products'
    | '/inventory/adjustments'
    | '/inventory/alerts'
    | '/inventory/consumption'
    | '/inventory/counts'
    | '/inventory/movements'
    | '/inventory/opening-stock'
    | '/inventory/reorder'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/offline/review'
    | '/settings/billing'
    | '/settings/business'
    | '/settings/receipts'
    | '/settings/security'
    | '/inventory'
    | '/locations'
    | '/notifications'
    | '/purchasing'
    | '/registers'
    | '/reports'
    | '/staff'
    | '/registers/$registerId/favourites'
    | '/inventory/batches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/plans'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/pos'
    | '/_authenticated/returns'
    | '/_authenticated/sales'
    | '/auth/google-callback'
    | '/invite/accept'
    | '/_authenticated/catalogue/categories'
    | '/_authenticated/catalogue/import'
    | '/_authenticated/catalogue/products'
    | '/_authenticated/inventory/adjustments'
    | '/_authenticated/inventory/alerts'
    | '/_authenticated/inventory/consumption'
    | '/_authenticated/inventory/counts'
    | '/_authenticated/inventory/movements'
    | '/_authenticated/inventory/opening-stock'
    | '/_authenticated/inventory/reorder'
    | '/_authenticated/inventory/stock'
    | '/_authenticated/inventory/transfers'
    | '/_authenticated/offline/review'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/business'
    | '/_authenticated/settings/receipts'
    | '/_authenticated/settings/security'
    | '/_authenticated/inventory/'
    | '/_authenticated/locations/'
    | '/_authenticated/notifications/'
    | '/_authenticated/purchasing/'
    | '/_authenticated/registers/'
    | '/_authenticated/reports/'
    | '/_authenticated/staff/'
    | '/_authenticated/registers/$registerId/favourites'
    | '/_authenticated/inventory/batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/google-callback': {
      id: '/auth/google-callback'
      path: '/auth/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalogue/categories': {
      id: '/_authenticated/catalogue/categories'
      path: '/catalogue/categories'
      fullPath: '/catalogue/categories'
      preLoaderRoute: typeof AuthenticatedCatalogueCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogue/import': {
      id: '/_authenticated/catalogue/import'
      path: '/catalogue/import'
      fullPath: '/catalogue/import'
      preLoaderRoute: typeof AuthenticatedCatalogueImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogue/products': {
      id: '/_authenticated/catalogue/products'
      path: '/catalogue/products'
      fullPath: '/catalogue/products'
      preLoaderRoute: typeof AuthenticatedCatalogueProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/adjustments': {
      id: '/_authenticated/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof AuthenticatedInventoryAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/alerts': {
      id: '/_authenticated/inventory/alerts'
      path: '/inventory/alerts'
      fullPath: '/inventory/alerts'
      preLoaderRoute: typeof AuthenticatedInventoryAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/consumption': {
      id: '/_authenticated/inventory/consumption'
      path: '/inventory/consumption'
      fullPath: '/inventory/consumption'
      preLoaderRoute: typeof AuthenticatedInventoryConsumptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/counts': {
      id: '/_authenticated/inventory/counts'
      path: '/inventory/counts'
      fullPath: '/inventory/counts'
      preLoaderRoute: typeof AuthenticatedInventoryCountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/movements': {
      id: '/_authenticated/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AuthenticatedInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/opening-stock': {
      id: '/_authenticated/inventory/opening-stock'
      path: '/inventory/opening-stock'
      fullPath: '/inventory/opening-stock'
      preLoaderRoute: typeof AuthenticatedInventoryOpeningStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/reorder': {
      id: '/_authenticated/inventory/reorder'
      path: '/inventory/reorder'
      fullPath: '/inventory/reorder'
      preLoaderRoute: typeof AuthenticatedInventoryReorderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/stock': {
      id: '/_authenticated/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AuthenticatedInventoryStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/transfers': {
      id: '/_authenticated/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AuthenticatedInventoryTransfersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offline/review': {
      id: '/_authenticated/offline/review'
      path: '/offline/review'
      fullPath: '/offline/review'
      preLoaderRoute: typeof AuthenticatedOfflineReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchasing/': {
      id: '/_authenticated/purchasing/'
      path: '/purchasing'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof AuthenticatedPurchasingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registers/': {
      id: '/_authenticated/registers/'
      path: '/registers'
      fullPath: '/registers/'
      preLoaderRoute: typeof AuthenticatedRegistersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/business': {
      id: '/_authenticated/settings/business'
      path: '/settings/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/receipts': {
      id: '/_authenticated/settings/receipts'
      path: '/settings/receipts'
      fullPath: '/settings/receipts'
      preLoaderRoute: typeof AuthenticatedSettingsReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/batches/': {
      id: '/_authenticated/inventory/batches/'
      path: '/inventory/batches'
      fullPath: '/inventory/batches/'
      preLoaderRoute: typeof AuthenticatedInventoryBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registers/$registerId/favourites': {
      id: '/_authenticated/registers/$registerId/favourites'
      path: '/registers/$registerId/favourites'
      fullPath: '/registers/$registerId/favourites'
      preLoaderRoute: typeof AuthenticatedRegistersRegisterIdFavouritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedCatalogueCategoriesRoute: typeof AuthenticatedCatalogueCategoriesRoute
  AuthenticatedCatalogueImportRoute: typeof AuthenticatedCatalogueImportRoute
  AuthenticatedCatalogueProductsRoute: typeof AuthenticatedCatalogueProductsRoute
  AuthenticatedInventoryAdjustmentsRoute: typeof AuthenticatedInventoryAdjustmentsRoute
  AuthenticatedInventoryAlertsRoute: typeof AuthenticatedInventoryAlertsRoute
  AuthenticatedInventoryConsumptionRoute: typeof AuthenticatedInventoryConsumptionRoute
  AuthenticatedInventoryCountsRoute: typeof AuthenticatedInventoryCountsRoute
  AuthenticatedInventoryMovementsRoute: typeof AuthenticatedInventoryMovementsRoute
  AuthenticatedInventoryOpeningStockRoute: typeof AuthenticatedInventoryOpeningStockRoute
  AuthenticatedInventoryReorderRoute: typeof AuthenticatedInventoryReorderRoute
  AuthenticatedInventoryStockRoute: typeof AuthenticatedInventoryStockRoute
  AuthenticatedInventoryTransfersRoute: typeof AuthenticatedInventoryTransfersRoute
  AuthenticatedOfflineReviewRoute: typeof AuthenticatedOfflineReviewRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsBusinessRoute: typeof AuthenticatedSettingsBusinessRoute
  AuthenticatedSettingsReceiptsRoute: typeof AuthenticatedSettingsReceiptsRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedPurchasingIndexRoute: typeof AuthenticatedPurchasingIndexRoute
  AuthenticatedRegistersIndexRoute: typeof AuthenticatedRegistersIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedRegistersRegisterIdFavouritesRoute: typeof AuthenticatedRegistersRegisterIdFavouritesRoute
  AuthenticatedInventoryBatchesIndexRoute: typeof AuthenticatedInventoryBatchesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedCatalogueCategoriesRoute: AuthenticatedCatalogueCategoriesRoute,
  AuthenticatedCatalogueImportRoute: AuthenticatedCatalogueImportRoute,
  AuthenticatedCatalogueProductsRoute: AuthenticatedCatalogueProductsRoute,
  AuthenticatedInventoryAdjustmentsRoute:
    AuthenticatedInventoryAdjustmentsRoute,
  AuthenticatedInventoryAlertsRoute: AuthenticatedInventoryAlertsRoute,
  AuthenticatedInventoryConsumptionRoute:
    AuthenticatedInventoryConsumptionRoute,
  AuthenticatedInventoryCountsRoute: AuthenticatedInventoryCountsRoute,
  AuthenticatedInventoryMovementsRoute: AuthenticatedInventoryMovementsRoute,
  AuthenticatedInventoryOpeningStockRoute:
    AuthenticatedInventoryOpeningStockRoute,
  AuthenticatedInventoryReorderRoute: AuthenticatedInventoryReorderRoute,
  AuthenticatedInventoryStockRoute: AuthenticatedInventoryStockRoute,
  AuthenticatedInventoryTransfersRoute: AuthenticatedInventoryTransfersRoute,
  AuthenticatedOfflineReviewRoute: AuthenticatedOfflineReviewRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsBusinessRoute: AuthenticatedSettingsBusinessRoute,
  AuthenticatedSettingsReceiptsRoute: AuthenticatedSettingsReceiptsRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedPurchasingIndexRoute: AuthenticatedPurchasingIndexRoute,
  AuthenticatedRegistersIndexRoute: AuthenticatedRegistersIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedRegistersRegisterIdFavouritesRoute:
    AuthenticatedRegistersRegisterIdFavouritesRoute,
  AuthenticatedInventoryBatchesIndexRoute:
    AuthenticatedInventoryBatchesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  InviteAcceptRoute: InviteAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
